In [1]:
import numpy as np

from src.models.train_emos import train_emos, train_and_test_emos
from pit import make_cpit_diagram_emos, make_cpit_hist_emos 
from brier_score import brier_skill_plot, brier_plot
from src.models.get_data import get_tensors, get_normalized_tensor
from src.models.emos import EMOS

2024-03-01 09:21:13.461849: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-01 09:21:13.488177: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-01 09:21:13.488196: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-01 09:21:13.488978: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-01 09:21:13.493193: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-01 09:21:13.493678: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
neighbourhood_size = 11
parameter_names = ['wind_speed', 'press', 'kinetic', 'humid', 'geopot']
ignore = ['229', '285', '323']
train_folds = [1, 2]
train_data = get_normalized_tensor(neighbourhood_size, parameter_names, train_folds, ignore)

X_train = train_data['X']
y_train = train_data['y']
variances_train = train_data['variances']
mean_train = train_data['mean']
std_train = train_data['std']


print(X_train.shape)

(15733, 5)


In [3]:
test_fold = 3

X_test, y_test, variances_test = get_tensors(neighbourhood_size, parameter_names, test_fold, ignore)
X_test = (X_test - mean_train) / std_train

print(X_test.shape)

(7780, 5)


In [4]:
setup = {}

setup["num_features"] = len(parameter_names)
setup["feature_mean"] = mean_train
setup["feature_std"] = std_train
setup["features"] = parameter_names
setup["neighbourhood_size"] = neighbourhood_size

In [7]:
setup1 = setup

setup1["loss"] = "loss_CRPS_sample"
setup1["samples"] = 100
setup1["optimizer"] = "Adam"
setup1["learning_rate"] = 0.01
setup1["forecast_distribution"] = "distr_trunc_normal"

trunc_normal_crps = EMOS(setup1)

Using default parameters for truncated normal distribution


In [8]:
trunc_normal_crps.fit(X_train, y_train, variances_train, 200, True)

Step: 0, Loss: 1.6884312629699707
Step: 1, Loss: 1.6674045324325562
Step: 2, Loss: 1.6425449848175049
Step: 3, Loss: 1.6212313175201416
Step: 4, Loss: 1.5989294052124023
Step: 5, Loss: 1.5796879529953003
Step: 6, Loss: 1.5594357252120972
Step: 7, Loss: 1.5428332090377808
Step: 8, Loss: 1.5268560647964478
Step: 9, Loss: 1.511104941368103
Step: 10, Loss: 1.4972862005233765
Step: 11, Loss: 1.4818412065505981
Step: 12, Loss: 1.469557285308838
Step: 13, Loss: 1.4578388929367065
Step: 14, Loss: 1.4444080591201782
Step: 15, Loss: 1.435276985168457
Step: 16, Loss: 1.422216534614563
Step: 17, Loss: 1.4115030765533447
Step: 18, Loss: 1.39873468875885
Step: 19, Loss: 1.3891730308532715
Step: 20, Loss: 1.3779594898223877
Step: 21, Loss: 1.3680294752120972
Step: 22, Loss: 1.3556177616119385
Step: 23, Loss: 1.3447786569595337
Step: 24, Loss: 1.336028814315796
Step: 25, Loss: 1.3241889476776123
Step: 26, Loss: 1.3140934705734253
Step: 27, Loss: 1.3037840127944946
Step: 28, Loss: 1.2944855690002441
St

[<tf.Tensor: shape=(), dtype=float32, numpy=1.6884313>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.6674045>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.642545>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.6212313>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5989294>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.579688>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5594357>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5428332>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5268561>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.511105>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4972862>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4818412>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4695573>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4578389>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.444408>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.435277>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4222165>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4115031

In [10]:
t = 0
make_cpit_hist_emos(trunc_normal_crps, X_test, y_test, variances_test, t=t)


AttributeError: 'TruncatedNormal' object has no attribute 'get_forecast'